# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, ardrone-autonomy, catkin, ros-foxglove-bridge, teleop-twist-joy , roscpp, rospy, std-msgs }:
buildRosPackage {
  pname = "ros-noetic-nix-ros-ardrone";
  version = "0.0.0";

  src = ./.;

  buildType = "catkin";
  buildInputs = [ catkin ];
  propagatedBuildInputs = [ ardrone-autonomy ros-foxglove-bridge teleop-twist-joy roscpp rospy std-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "This package contains launch files and configurations for setting up the AR.Drone with various ROS components.";
    license = with lib.licenses; [ mit ];
  };
}
