# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, catkin, cv-bridge, eigen, geometry-msgs, glog, image-transport, message-filters, nav-msgs, pcl-ros, sensor-msgs, stella-vslam, tf2, tf2-eigen, tf2-geometry-msgs, tf2-msgs, tf2-ros, yaml-cpp, g2o, libGL, libGLU, socket-publisher, suitesparse, fetchFromGitHub }:
buildRosPackage rec {
  pname = "ros-noetic-stella-vslam-ros";
  version = "07-04-2025";

  src = fetchFromGitHub {
    owner = "stella-cv";
    repo = "stella_vslam_ros";
    rev = "f943ff7b2af3935b44dd31014c5532bb199f76dc"; # branch ros
    fetchSubmodules = true;
    sha256 = "sha256-JPM7AGRtzV9ZiTxXa8dNL6hCFho1NzZxN+9Oim9lXP4=";
  };

  patches = [ ./good.patch ];

  buildType = "catkin";
  buildInputs = [ catkin g2o libGL libGLU socket-publisher suitesparse ];
  propagatedBuildInputs = [ cv-bridge eigen geometry-msgs glog image-transport message-filters nav-msgs pcl-ros sensor-msgs stella-vslam tf2 tf2-eigen tf2-geometry-msgs tf2-msgs tf2-ros yaml-cpp ];
  nativeBuildInputs = [ catkin ];
  NIX_ENFORCE_NO_NATIVE = 0;

  meta = {
    description = "The ROS package for stella_vslam";
    license = with lib.licenses; [ "2-clause-BSD" ];
  };
}
