# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, catkin, cv-bridge, dynamic-reconfigure, image-transport, message-generation, message-runtime, roscpp, rospy, sensor-msgs, std-msgs, tf, tf2-geometry-msgs, tf2-ros, fetchFromGitHub }:
buildRosPackage rec {
  pname = "ros-noetic-orb-slam2-ros";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "appliedAI-Initiative";
    repo = "orb_slam_2_ros";
    rev = "e933256610f3648e5cd96e549df84cfe40f9b812";
    sha256 = "sha256-uuN3Elu3Fr90YPrT4Y3YMcBXX/Pdc+NIjQHi083eyyg=";
  };

  patches = [ ./good.patch ];

  buildType = "catkin";
  buildInputs = [ catkin message-generation tf2-geometry-msgs tf2-ros ];
  propagatedBuildInputs = [ cv-bridge dynamic-reconfigure image-transport message-runtime roscpp rospy sensor-msgs std-msgs tf ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "ORB SLAM2 ros implementation.";
    license = with lib.licenses; [ gpl3Only ];
  };
}
