# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, catkin, message-filters, pluginlib, rosconsole, roscpp, roslib, sensor-msgs, fetchFromGitHub }:
buildRosPackage rec {
  pname = "ros-noetic-image-transport-overlayed";
  version = "1.12.1";

  src = fetchFromGitHub {
    owner = "ros-perception";
    repo = "image_common";
    rev = version;
    sha256 = "sha256-t6jWlWS+x8BdPUPBTY8myekthIbS8m+Ggt658W9XmS0=";
  };

  sourceRoot = "source/image_transport";

  buildType = "catkin";
  buildInputs = [ catkin ];
  propagatedBuildInputs = [ message-filters pluginlib rosconsole roscpp roslib sensor-msgs ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "image_transport should always be used to subscribe to and publish images. It provides transparent
     support for transporting images in low-bandwidth compressed formats. Examples (provided by separate
     plugin packages) include JPEG/PNG compression and Theora streaming video.";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
