axis_linear:
  x: 1   # Forward/Backward (Joystick Y-axis)
  y: 0   # Left/Right (Joystick X-axis)
  z: 2   # Up/Down (Throttle)
axis_angular: 4
scale_linear:
  x: 0.7
  y: 0.7
  z: 0.7
scale_angular: 0.7   # Rotation sensitivity
enable_button: 0     # Trigger button (enable control)
